name: test-pypi
on:
  push:
    branches: [master]

jobs:
  test-pypi:
    if: github.repository == 'Gitruck/flet-search-bar'
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/gitruck-flet-search-bar/
    permissions:
      id-token: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: 3.9
      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build distribution
        run: >-
          python -m
          build
          --sdist
          --wheel
          --outdir dist/
          .
      - name: Publish distribution to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
